package com.kira.tts

/** MAV_CMD names for COMMAND_LONG / COMMAND_INT decoding in the monitor. */
object MavCmd {
    private val NAMES: Map<Int, String> = mapOf(
        16 to "NAV_WAYPOINT",
        17 to "NAV_LOITER_UNLIM",
        18 to "NAV_LOITER_TURNS",
        19 to "NAV_LOITER_TIME",
        20 to "NAV_RETURN_TO_LAUNCH",
        21 to "NAV_LAND",
        22 to "NAV_TAKEOFF",
        82 to "NAV_SPLINE_WAYPOINT",
        84 to "NAV_VTOL_TAKEOFF",
        85 to "NAV_VTOL_LAND",
        92 to "NAV_GUIDED_ENABLE",
        93 to "NAV_DELAY",
        112 to "CONDITION_DELAY",
        113 to "CONDITION_CHANGE_ALT",
        114 to "CONDITION_DISTANCE",
        115 to "CONDITION_YAW",
        176 to "DO_SET_MODE",
        177 to "DO_JUMP",
        178 to "DO_CHANGE_SPEED",
        179 to "DO_SET_HOME",
        181 to "DO_SET_RELAY",
        183 to "DO_SET_SERVO",
        189 to "DO_LAND_START",
        192 to "DO_REPOSITION",
        193 to "DO_PAUSE_CONTINUE",
        201 to "DO_SET_ROI",
        203 to "DO_DIGICAM_CONTROL",
        205 to "DO_MOUNT_CONTROL",
        206 to "DO_SET_CAM_TRIGG_DIST",
        207 to "DO_FENCE_ENABLE",
        208 to "DO_PARACHUTE",
        209 to "DO_MOTOR_TEST",
        213 to "DO_GRIPPER",
        220 to "DO_SET_CAM_TRIGG_INTERVAL",
        241 to "PREFLIGHT_CALIBRATION",
        246 to "PREFLIGHT_REBOOT_SHUTDOWN",
        300 to "MISSION_START",
        400 to "COMPONENT_ARM_DISARM",
        401 to "RUN_PREARM_CHECKS",
        500 to "START_RX_PAIR",
        510 to "GET_MESSAGE_INTERVAL",
        511 to "SET_MESSAGE_INTERVAL",
        519 to "REQUEST_PROTOCOL_VERSION",
        520 to "REQUEST_AUTOPILOT_CAPABILITIES",
        521 to "REQUEST_CAMERA_INFORMATION",
        522 to "REQUEST_CAMERA_SETTINGS",
        525 to "REQUEST_STORAGE_INFORMATION",
        531 to "REQUEST_FLIGHT_INFORMATION",
        2000 to "IMAGE_START_CAPTURE",
        2001 to "IMAGE_STOP_CAPTURE",
        2003 to "DO_TRIGGER_CONTROL",
        2500 to "VIDEO_START_CAPTURE",
        2501 to "VIDEO_STOP_CAPTURE",
        2502 to "VIDEO_START_STREAMING",
        2503 to "VIDEO_STOP_STREAMING",
        3000 to "SET_CAMERA_MODE",
        3001 to "SET_CAMERA_ZOOM",
        3002 to "SET_CAMERA_FOCUS",
    )

    fun name(cmd: Int): String = NAMES[cmd] ?: "CMD_$cmd"
}
